name: Deploy to Pages

on:
  push:
    branches:
      - "prod"
    paths:
      - "web/**"
      - ".github/**"
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Install fd
        uses: baptiste0928/cargo-install@v1
        with:
          crate: fd-find
      - name: Install yj
        uses: baptiste0928/cargo-install@v1
        with:
          crate: yj
      - name: Install jinja2
        run: pip install jinja2-cli
      - name: Build Site
        id: build
        run: make site
      - name: Upload artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: "web/out"

  deploy:
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@main
